size:
  width: 10
  height: 10
  scale: 1.0
walls:
  - name: wall1
    pose: [0.0,0.0]
    shape: [10,0]
    width: 0.1
  - name: wall2
    pose: [0.0,10.0]
    shape: [10,0]
    width: 0.1
  # - name: wall3
  #   pose: [0.0,10]
  #   shape: [10,0]
  #   width: 1
  - name: wall4
    pose: [4.5,5]
    shape: [0.5,0]
    width: 0.5
  - name: wall5
    pose: [4,0.0]
    shape: [0,10]
    width: 0.3
  - name: wall6
    pose: [5,3]
    shape: [0.5,0]
    width: 0.5
  - name: wall7
    pose: [6,0]
    shape: [0,10]
    width: 0.3
  - name: wall8
    pose: [4.0,6.0]
    shape: [1.0,1.0]
    width: 0.3

nodes:
  - name: node1
    pose: [2,3.0]
  - name: node2
    pose: [3,3]
  - name: node3
    pose: [7,3]
  - name: node4
    pose: [3,7]
  - name: node5
    pose: [7,7]

zones:
  - name: zone1
    pose: [4.5,1.1]
    shape: [1,0]
    width: 1.0
  - name: zone2
    pose: [4.5,8.9]
    shape: [1,0]
    width: 1

viewer:
  show_nodes: false
  show_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 0
  convergence_radius: 1.0
agent:
  config_rel_path: default1.yml
  max_agent_num: 1
