size:
  width: 10
  height: 10
  scale: 1.0
walls:
  - name: wall1
    pose: [0.0,0.0]
    shape: [0,10]
    width: 1
  - name: wall2
    pose: [0.0,0.0]
    shape: [10,0]
    width: 1
  - name: wall3
    pose: [0.0,10]
    shape: [10,0]
    width: 1
  - name: wall4
    pose: [10,0]
    shape: [0,10]
    width: 1
  - name: wall5
    pose: [2.5,4.5]
    shape: [0,2]
    width: 0.5
  - name: wall6
    pose: [4.0,7.0]
    shape: [2,0]
    width: 0.5
  - name: wall7
    pose: [7.5,4.5]
    shape: [0,2]
    width: 0.5
  - name: wall8
    pose: [4.0,4.0]
    shape: [2.0,0]
    width: 0.5
  - name: wall9
    pose: [1.5,1.5]
    shape: [.5,0]
    width: 0.5
  # - name: wall10
  #   pose: [3.0,2.0]
  #   shape: [.5,0]
  #   width: 0.5
  # - name: wall11
  #   pose: [4,2.5]
  #   shape: [.5,0]
  #   width: 0.5
  - name: wall12
    pose: [8.5,1.5]
    shape: [.5,0]
    width: 0.5
  - name: wall13
    pose: [8,2.0]
    shape: [.5,0]
    width: 0.5
  # - name: wall14
  #   pose: [7,2.5]
  #   shape: [.5,0]
  #   width: 0.5
  - name: wall15
    pose: [1.5,8.5]
    shape: [.5,0]
    width: 0.5
  - name: wall16
    pose: [3.0,8.0]
    shape: [.5,0]
    width: 0.5
  # - name: wall17
  #   pose: [3,7.0]
  #   shape: [.5,0]
  #   width: 0.5
  - name: wall18
    pose: [8.5,8.5]
    shape: [.5,0]
    width: 0.5
  # - name: wall19
  #   pose: [7,7.0]
  #   shape: [.5,0]
  #   width: 0.5
  - name: wall20
    pose: [8,8.0]
    shape: [.5,0]
    width: 0.5

nodes:
  - name: node1
    pose: [2,3.0]
  - name: node2
    pose: [3,3]
  - name: node3
    pose: [7,3]
  - name: node4
    pose: [3,7]
  - name: node5
    pose: [7,7]

zones:
  - name: zone1
    pose: [4.5,1.5]
    shape: [1,0]
    width: 1.0
  - name: zone2
    pose: [4.5,8.5]
    shape: [1,0]
    width: 1
  - name: zon32
    pose: [4.5,5.5]
    shape: [1,0]
    width: 1

viewer:
  show_nodes: false
  show_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 0
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1
