size:
  width: 40
  height: 20
  scale: 0.8
walls:
  - name: wall1
    pose: [0.5,0.0]
    shape: [0,20]
    width: 1
  - name: wall2
    pose: [0.5,19]
    shape: [9,0]
    width: 1
  - name: wall3
    pose: [12,19]
    shape: [14,0]
    width: 1
  - name: wall4
    pose: [29,19]
    shape: [11,0]
    width: 1
  - name: wall5
    pose: [0.5,20]
    shape: [40,0]
    width: 1
  - name: wall6
    pose: [39.5,0.0]
    shape: [0,20]
    width: 1
  - name: wall7
    pose: [0.5,1.0]
    shape: [9,0]
    width: 1
  - name: wall8
    pose: [12,1.0]
    shape: [14,0]
    width: 1
  - name: wall9
    pose: [29,1.0]
    shape: [11,0]
    width: 1
  - name: wall10
    pose: [0.5,0]
    shape: [40,0]
    width: 1
  - name: wall11
    pose: [0.5,0]
    shape: [40,0]
    width: 1
  - name: wall12
    pose: [3.0,14]
    shape: [13,0]
    width: 5
  - name: wall13
    pose: [23.0,14]
    shape: [13,0]
    width: 5
  - name: wall14
    pose: [3.0,6.0]
    shape: [13,0]
    width: 5
  - name: wall15
    pose: [23.0,6.0]
    shape: [13,0]
    width: 5

nodes:
  - name: node1
    pose: [20,17.5]
  - name: node2
    pose: [20,2.0]
  - name: node3
    pose: [38,17.5]
  - name: node4
    pose: [38,2.0]
  - name: node5
    pose: [20,2.0]
  - name: node6
    pose: [2.0,2.0]
  - name: node7
    pose: [2.0,17.5]
  - name: node8
    pose: [2.0,10]
  - name: node9
    pose: [38,2.0]
  - name: node10
    pose: [38,10]
  - name: node11
    pose: [20,10]
  - name: node12
    pose: [9,17.5]
  - name: node13
    pose: [25,17.5]
  - name: node14
    pose: [9,3.0]
  - name: node15
    pose: [25,3.0]
  - name: node16
    pose: [16,12]
  - name: node17
    pose: [16,8]
  - name: node18
    pose: [24,12]
  - name: node19
    pose: [24,8]
  - name: node20
    pose: [12,17.5]
  - name: node21
    pose: [29,17.5]
  - name: node22
    pose: [12,3.0]
  - name: node23
    pose: [29,3.0]

zones:
  - name: zone1
    pose: [11.0,18.7]
    shape: [1,0]
    width: 1.0
  - name: zone2
    pose: [27,18.7]
    shape: [1,0]
    width: 1
  - name: zone3
    pose: [11,1.0]
    shape: [0,1]
    width: 1
  - name: zone4
    pose: [27,1.0]
    shape: [0,1]
    width: 1
  - name: zone5
    pose: [1.0,10]
    shape: [1,0]
    width: 4
  - name: zone6
    pose: [38,10]
    shape: [1,0]
    width: 4
viewer:
  show_nodes: false
  show_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 0
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1
