size:
  width: 10
  height: 10
  scale: 1.0
walls:
  - name: wall1
    pose: [4.5,6.0]
    shape: [0,0.6]
    width: 0.3
  - name: wall2
    pose: [5,5.0]
    shape: [0,0.5]
    width: .5
  - name: wall3
    pose: [3.0,8]
    shape: [0.6,0]
    width: 0.6
  - name: wall4
    pose: [3.0,2.0]
    shape: [1.0,0.5]
    width: .3
  - name: wall5
    pose: [2.5,0.0]
    shape: [0,10]
    width: 0.3
  # - name: wall6
  #   pose: [4.5,7]
  #   shape: [3.0,0]
  #   width: 0.3
  - name: wall7
    pose: [7.5,0]
    shape: [0,10]
    width: 0.3
  - name: wall8
    pose: [2.5,4]
    shape: [3.0,0]
    width: 0.3
  - name: wall9
    pose: [6.5,3]
    shape: [.4,0]
    width: 0.4
  - name: wall10
    pose: [6.5,6.5]
    shape: [.4,0]
    width: 0.4

nodes:
  - name: node1
    pose: [2,3.0]
  # - name: node2
  #   pose: [3,3]
  # - name: node3
  #   pose: [7,3]
  # - name: node4
  #   pose: [3,7]
  # - name: node5
  #   pose: [7,7]

zones:
  - name: zone1
    pose: [4.5,2.0]
    shape: [1,0]
    width: 1.0
  - name: zone2
    pose: [4.5,8.0]
    shape: [1,0]
    width: 1

viewer:
  show_nodes: false
  show_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 0
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1
