agent:
  v: 0.0      # [m/s]
  omega: 0.0  # [rad/s]

  max_v: 0.4      # [m/s]
  min_v: 0.0      # [m/s]
  max_omega: 1.0  # [rad/s]

  name: agent
  color: [0, 0, 255]        # RGB
  mass: 60                  # [kg]
  radius: 0.25              # [m]
  lidar_linear_range: 40.0  # [m]
  lidar_rad_range: 180.0    # [deg]
  lidar_rad_step: 0.4       # [deg]
