size:
  width: 10
  height: 10
  scale: 1.0
walls:
  - name: wall1
    pose: [0.0,0.0]
    shape: [0,10]
    width: 1
  - name: wall2
    pose: [0.0,0.0]
    shape: [10,0]
    width: 1
  - name: wall3
    pose: [0.0,10]
    shape: [10,0]
    width: 1
  - name: wall4
    pose: [10,0]
    shape: [0,10]
    width: 1
  - name: wall5
    pose: [3.5,3.5]
    shape: [0,3.5]
    width: 0.5
  - name: wall6
    pose: [3.3,5.25]
    shape: [3.4,0]
    width: 0.5
  - name: wall7
    pose: [6.5,3.5]
    shape: [0,3.5]
    width: 0.5
  # - name: wall8
  #   pose: [3.5,6.5]
  #   shape: [1.0]
  #   width: 0.5

nodes:
  - name: node1
    pose: [5,5]
  - name: node2
    pose: [2,5]
  - name: node3
    pose: [8,5]
  # - name: node4
  #   pose: [38,2.0]
  # - name: node5
  #   pose: [20,2.0]

zones:
  - name: zone1
    pose: [4.3,1.1]
    shape: [1,0]
    width: 1.0
  - name: zone2
    pose: [4.3,8.9]
    shape: [1,0]
    width: 1

viewer:
  show_nodes: false
  show_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 0
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1
